# Generated by Django 2.1.5 on 2019-01-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50)),
                ('sexe', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=5)),
                ('cin', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone_tuteur', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('date_de_naissance', models.DateField(blank=True)),
                ('etablissement', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.Annee')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.Filiere')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleve.Module'),
        ),
    ]
